#!/usr/bin/env bash

set -u

# TODO: support other OS'.
SYSTEM_OS=darwin

BREW_PATH=${HOME}/.homebrew
BREW_URL=https://github.com/Homebrew/brew/tarball/master

GO_VERSION=1.13.3
GO_URL=https://dl.google.com/go/go${GO_VERSION}.${SYSTEM_OS}-amd64.tar.gz

RAILS_VERSION=6.0.0
RUBY_VERSION=2.6.5

RUST_URL=https://sh.rustup.rs

usage() {
    cat 1>&2 <<EOF
dotfiles-init 0.0.1 (2019-10-09)
Dotfiles installer.

USAGE:
    dotfiles-init [FLAGS] [OPTIONS]

FLAGS:
    -v, --verbose           Enable verbose output
    -y                      Disable confirmation prompt
        --no-modify-path    Don't configure the PATH environment variable
    -h, --help              Prints help information
    -V, --version           Prints version information

OPTIONS:
    --no-options            Default, no options available now.
EOF
}

main() {
  need_cmd curl

  for arg in "$@"; do
    case "$arg" in
      -h|--help)
        usage
        exit 0
        ;;
      -y)
        need_tty=no
        ;;
      *)
        ;;
    esac
  done

  install_homebrew
  install_stow
  install_go
  install_rust
  install_vim
}

say() {
  printf 'dotfiles: %s\n' "$1"
}

err() {
  say "$1" >&2
  exit 1
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

check_cmd() {
  command -v "$1" > /dev/null 2>&1
}

assert_nz() {
  if [ -z "$1" ]; then
    err "assert_nz $2"
  fi
}

ensure() {
  if ! "$@"; then err "command failed: $*";fi
}

ignore() {
  "$@"
}

install_homebrew() {
  check_cmd brew && return
  mkdir ${BREW_PATH} && curl -L ${BREW_URL} | tar xz --strip 1 -C ${BREW_PATH}
}

install_go() {
  # might be easier using Homebrew/apt-get?
  need_cmd brew

  brew install golang
  mkdir ${HOME}/go
}

install_ruby() {
  need_cmd brew

  brew install rbenv ruby-build
  source $HOME/.bash_profile
  rbenv install ${RUBY_VERSION}
  rbenv global ${RUBY_VERSION}

  gem install rails -v ${RAILS_VERSION}
  rbenv rehash
}

install_rust() {
  curl ${RUST_URL} -sSf | sh -s -- -y
}

install_stow() {
  need_cmd brew
  brew install stow
}

install_vim() {
  need_cmd brew
  need_cmd stow

  brew install vim neovim
  pushd nvim
  stow -t ~/.config/nvim nvim  
  ln -s ~/.config/nvim ~/.vim
  ln -s ~/.vim/init.vim ~/.vimrc
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +PlugInstall +qall
  nvim +PlugInstall +qall
  popd
}

main "$@" | exit 1
